### ISSUE TITLE
qemu seems to hang on `Booting from Hard Disk...`

### ISSUE THREAD

**Issue by daveloyall** [NieDzejkob/miniforth#3]
Hi.

Neat project, thanks!

Let's say I started here...

```
sebboh@debian:~/prj/miniforth$ git status && rm -v boot.bin boot.lst disk.img raw.bin && \
yasm -f bin boot.s -o raw.bin -l boot.lst && python3 compress.py && python3 mkdisk.py
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        boot.bin
        boot.lst
        disk.img
        raw.bin

nothing added to commit but untracked files present (use "git add" to track)
removed 'boot.bin'
removed 'boot.lst'
removed 'disk.img'
removed 'raw.bin'
504 bytes used
Found 6 block files
sebboh@debian:~/prj/miniforth$
```

Then, I invoke `run.sh`.

I get this screen and put some input in but I do not get output when I hit enter:

```
SeaBIOS (version 1.14.0-2)


iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+xxxxxxxx+xxxxxxxx xxxx



Booting from Hard Disk...
1 1 +
```

So, I attempt to gather some information about what it is doing.  I hit `alt+2` and type a command:

```
compat_monitor0 console
QEMU 5.2.0 monitor - type 'help' for more information
(qemu) xp /20xi 0
0x00000000:  53                       pushw    %bx
0x00000001:  ff 00                    incw     (%bx, %si)
0x00000003:  f0                       .byte    0xf0
0x00000004:  53                       pushw    %bx
0x00000005:  ff 00                    incw     (%bx, %si)
0x00000007:  f0                       .byte    0xf0
0x00000008:  c3                       retw
0x00000009:  e2 00                    loop     0xb
0x0000000b:  f0                       .byte    0xf0
0x0000000c:  53                       pushw    %bx
0x0000000d:  ff 00                    incw     (%bx, %si)
0x0000000f:  f0                       .byte    0xf0
0x00000010:  53                       pushw    %bx
0x00000011:  ff 00                    incw     (%bx, %si)
0x00000013:  f0                       .byte    0xf0
0x00000014:  54                       pushw    %sp
0x00000015:  ff 00                    incw     (%bx, %si)
0x00000017:  f0                       .byte    0xf0
0x00000018:  53                       pushw    %bx
0x00000019:  ff 00                    incw     (%bx, %si)
(qemu)
```

Seems repetitive!  Hm, I don't know many qemu monitor commands nor how to interpret the output of this one.  @NieDzejkob or anyone, I'd be happy to gather more information and paste it here if you tell me how.  Or if enough information is present already, then let's call this a bug report? :)

Cheers, thank you,
--sebboh

**Comment by NieDzejkob** [comment]
> I get this screen and put some input in but I do not get output when I hit enter:

Unfortunately, I couldn't fit in a prompt, and you didn't include anything that would print the result. Try `1 1 + u.`, or `1 load` and then `words` on the next line (though pull the repo first, I pushed my changes which, among other things, make `1 load` load everything instead of needing to do `1 load`, `2 load`, and so on).

Some other remarks: echoing your input onto the screen is handled by Miniforth itself, too, so the mere fact that you see what you're typing on screen means that it didn't hang.

> I don't know many qemu monitor commands nor how to interpret the output of this one.

`xp /20xi 0` means you're inspecting the instructions at address zero. That doesn't make much sense, as at address zero, there's the IVT - a table of pointers to interrupt handlers.

A quick crash course on QEMU monitor commands:

`p/x $eip` - print the value of a register. Even though Miniforth runs in real mode, you need to use the 32-bit register names. QEMU just doesn't know about `ax` and `al`.
`x/10i $eip` - print the next 10 instructions that will be executed
`x/16xh $esp` - print 16 half-words starting at `$esp`.

**Comment by daveloyall** [comment]
Everything is as you described, and thank you for the tips!  I'm marking this as closed, since there was no problem; I just didn't know how to use it.
